import './style.css';

const APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycby2DyI3R8U8ah5GWkYyiy4kz80VC9dtjtvBFkO3DRmAJpGGKAy_IrJ30PvL5e2Wf229rw/exec';

const sharedPlatforms = ['Google Workspace','Microsoft 365','QuickBooks','Mailchimp','HubSpot','Salesforce','Square','Stripe','PayPal','Shopify','WordPress','Wix','Squarespace','Canva','Make','Zapier','Other'];

const industries = {
  beauty: { label:'Hair, beauty, and personal care', types:['Independent stylist or barber','Salon or barbershop','Nail business','Lash or brow business','Esthetics or skincare','Spa or wellness studio','Makeup artist','Mobile beauty professional','Beauty product brand','Multi-service beauty business'], platforms:['GlossGenius','Vagaro','Square Appointments','Fresha','Booksy','StyleSeat','Mindbody','Boulevard','Shopify','Square','Stripe','QuickBooks'], customer:['Browse services and pricing','Book appointments','Pay deposits or balances','Complete intake forms','Reschedule or cancel','Join a waitlist','Buy products','Purchase gift cards','Manage memberships','Rebook previous services'], owner:['Manage services and prices','Control calendars and availability','Manage staff schedules','Store client profiles and history','Collect forms and waivers','Track deposits and payments','Manage products and inventory','Send reminders and promotions','Track memberships and packages','View business reports'], problems:['Too many separate platforms','High monthly software costs','Customers leave the branded website to book','Too many no-shows or late cancellations','Deposits are inconsistent','Client information is spread across systems','Product and service sales are disconnected','Staff permissions are difficult to manage','Marketing follow-up is too manual','Reporting is limited'] },
  professional: { label:'Professional and local services', types:['Consulting','Legal services','Accounting or bookkeeping','Insurance or financial services','Marketing or creative agency','Business services','Repair or local service','Transportation or logistics','Security services','Other professional service'], platforms:['Calendly','Acuity Scheduling','HubSpot','Salesforce','HoneyBook','Dubsado','QuickBooks','Google Workspace','Microsoft 365','DocuSign','Stripe','Square'], customer:['Learn about services','Request a consultation','Book an appointment','Request a quote','Upload documents','Sign agreements','Pay invoices or deposits','Track project status','Access a client portal','Contact the business'], owner:['Manage leads and contacts','Create proposals and estimates','Schedule appointments','Send contracts','Collect payments','Manage projects and tasks','Store documents','Automate follow-up','Assign staff access','View sales and performance reports'], problems:['Leads are not followed up consistently','Information is spread across email and spreadsheets','Quoting takes too long','Scheduling is too manual','Contracts and payments are disconnected','Clients cannot see project status','Staff handoffs are inconsistent','Reporting is limited','The website does not explain the offer clearly','Too many tools are required'] },
  retail: { label:'Retail and e-commerce', types:['Online store','Physical retail store','Hybrid online and physical store','Product brand','Subscription box','Wholesale business','Marketplace seller','Boutique','Specialty retailer','Other retail business'], platforms:['Shopify','WooCommerce','Square','Clover','Lightspeed','BigCommerce','Etsy','Amazon Seller','Stripe','PayPal','QuickBooks','Mailchimp'], customer:['Browse products','Search and filter products','Buy online','Choose shipping or pickup','Create an account','Track orders','Use discounts or gift cards','Join a loyalty program','Subscribe to products','Contact customer support'], owner:['Manage products and variants','Track inventory','Process orders and refunds','Manage shipping and pickup','Create discounts','Manage customer accounts','Run loyalty or subscriptions','Send abandoned-cart follow-up','Sync point of sale','View sales reports'], problems:['Inventory does not stay synchronized','Checkout abandonment is high','Online and in-store sales are disconnected','Shipping is difficult to manage','Product updates take too long','Customer follow-up is limited','Reporting is fragmented','The store is slow or difficult on mobile','Monthly app costs are too high','Wholesale and retail workflows conflict'] },
  food: { label:'Food, restaurant, and hospitality', types:['Restaurant','Cafe or coffee shop','Bakery','Food truck','Catering business','Bar or nightlife venue','Hotel or lodging','Meal preparation service','Private chef','Other hospitality business'], platforms:['Toast','Square','Clover','DoorDash','Uber Eats','Grubhub','OpenTable','Resy','SevenRooms','Tock','Shopify','QuickBooks'], customer:['View menus','Order for pickup','Order delivery','Make a reservation','Join a waitlist','Request catering','Buy gift cards','Join a loyalty program','Book an event','Contact the business'], owner:['Manage menus and pricing','Receive online orders','Manage reservations and tables','Coordinate delivery and pickup','Track catering inquiries','Manage events','Run loyalty and gift cards','Manage staff access','Track inventory','View sales reports'], problems:['Menus are difficult to update','Ordering platforms charge too much','Reservations and walk-ins are disconnected','Delivery orders are hard to manage','Catering leads are missed','Customer data belongs to third-party platforms','Gift cards and loyalty are disconnected','The website does not convert visitors','Staff uses too many systems','Reporting is fragmented'] },
  wellness: { label:'Healthcare, fitness, and wellness', types:['Medical or dental practice','Mental health practice','Fitness studio or gym','Personal trainer','Wellness coach','Massage therapy','Chiropractic practice','Nutrition business','Home care service','Other wellness business'], platforms:['Mindbody','Jane App','SimplePractice','TherapyNotes','Vagaro','Trainerize','WellnessLiving','Acuity Scheduling','Calendly','Stripe','Square','QuickBooks'], customer:['View services or programs','Book appointments or classes','Complete intake forms','Pay balances or memberships','Access secure resources','Join a waitlist','Manage appointments','Receive reminders','Purchase packages','Contact the practice'], owner:['Manage providers and schedules','Store client or patient records','Collect forms and consent','Manage classes or programs','Track memberships and packages','Collect payments','Send reminders','Manage staff permissions','Create reports','Maintain privacy controls'], problems:['Scheduling is too manual','No-shows are too frequent','Forms are still handled on paper','Memberships are hard to track','Client information is fragmented','The website and practice software feel disconnected','Staff access is difficult to manage','Reporting is limited','Follow-up is inconsistent','Current software is too expensive'] },
  construction: { label:'Construction, trades, and home services', types:['General contractor','HVAC','Plumbing','Electrical','Roofing','Landscaping','Cleaning service','Property maintenance','Remodeling','Other trade or home service'], platforms:['Jobber','Housecall Pro','ServiceTitan','Buildertrend','Procore','QuickBooks','CompanyCam','Joist','Angi','Thumbtack','Google Workspace','Square'], customer:['Request an estimate','Book a service call','Upload project photos','Approve estimates','Sign agreements','Pay deposits or invoices','Track job status','Receive appointment updates','Request emergency service','Leave a review'], owner:['Manage leads and estimates','Schedule crews','Dispatch technicians','Track jobs and work orders','Store photos and documents','Manage materials or inventory','Collect signatures and payments','Automate customer updates','Manage staff access','View job profitability'], problems:['Leads are lost or answered slowly','Estimating takes too long','Scheduling and dispatch are manual','Job photos are disorganized','Customers repeatedly ask for updates','Invoices are paid late','Field and office teams are disconnected','Reporting is limited','The website does not generate qualified leads','Too many platforms are required'] },
  realestate: { label:'Real estate and property services', types:['Real estate agent or team','Brokerage','Property management','Real estate investor','Property development','Commercial real estate','Vacation rental','Home inspection','Mortgage or title service','Other property business'], platforms:['Zillow','Realtor.com','MLS','Follow Up Boss','kvCORE','BoomTown','AppFolio','Buildium','Yardi','DocuSign','QuickBooks','Mailchimp'], customer:['Browse properties','Request a showing','Submit an application','Schedule a consultation','Upload documents','Pay rent or fees','Submit maintenance requests','Track an application','Access an owner or tenant portal','Contact an agent'], owner:['Manage leads and properties','Schedule showings','Track applicants or tenants','Collect documents and signatures','Manage rent and payments','Track maintenance requests','Automate follow-up','Manage agents or staff','Publish listings','View property and sales reports'], problems:['Leads are not routed quickly','Listings are difficult to maintain','Follow-up is inconsistent','Applications require too much manual work','Documents are spread across systems','Tenant communication is inefficient','Maintenance requests are disorganized','Owner reporting takes too long','The website does not build enough trust','Software costs are too high'] },
  nonprofit: { label:'Nonprofit and community organization', types:['Charitable nonprofit','Foundation','Church or faith organization','Community program','Membership organization','Advocacy organization','Youth organization','Cultural organization','Professional association','Other nonprofit'], platforms:['Bloomerang','Donorbox','Givebutter','Classy','Network for Good','Salesforce Nonprofit Cloud','Eventbrite','Jotform','Mailchimp','Google Workspace','QuickBooks','PayPal'], customer:['Learn about the mission','Donate','Register for programs','Volunteer','Apply for assistance','Join as a member','Buy event tickets','Access resources','Sponsor an initiative','Contact the organization'], owner:['Manage donors and supporters','Track programs and participants','Manage volunteers','Create events and registrations','Collect applications','Send updates and campaigns','Manage memberships','Track grants or sponsorships','Assign staff access','Create impact reports'], problems:['Donor information is fragmented','Program registration is too manual','Volunteer coordination is difficult','Applications are tracked in spreadsheets','Event tools do not connect','Supporters receive inconsistent follow-up','Impact reporting takes too long','The website does not explain the mission clearly','Staff permissions are unclear','Monthly platform costs are too high'] },
  sports: { label:'Sports, events, and recreation', types:['Youth sports league','Sports clinic or camp','Tournament operator','Fitness or recreation program','Sports facility','Athlete development business','Event production company','Club or membership program','Sports media brand','Other sports or event business'], platforms:['TeamSnap','SportsEngine','LeagueApps','Eventbrite','Jotform','PlayMetrics','Mindbody','Square','Stripe','Mailchimp','Google Workspace'], customer:['Register participants','Buy tickets','Sign waivers','Make payments','View schedules','Receive updates','Join a team or program','Apply to volunteer or coach','Buy merchandise','Access event information'], owner:['Manage registrations','Create teams or groups','Build schedules','Track payments','Collect waivers and documents','Check in participants','Send reminders','Manage coaches or volunteers','Track sponsors','View participation reports'], problems:['Registration requires too many steps','Parent or participant records are duplicated','Payments and registrations do not match','Schedules are difficult to publish','Waivers are hard to track','Check-in is too slow','Messages are sent manually','Coach and volunteer access is confusing','Sponsor information is disorganized','Reporting is incomplete'] },
  education: { label:'Education, coaching, and training', types:['School or academy','Tutor or tutoring center','Online course business','Coach or consultant','Training company','Certification program','Childcare or enrichment program','Workshop provider','Professional development organization','Other education business'], platforms:['Teachable','Thinkific','Kajabi','Moodle','Canvas','Google Classroom','Calendly','Zoom','Eventbrite','Jotform','Stripe','Mailchimp'], customer:['Browse programs or courses','Enroll or apply','Schedule sessions','Make payments','Access lessons or resources','Submit assignments or documents','Track progress','Receive certificates','Join a community','Contact an instructor'], owner:['Manage courses and programs','Enroll students','Schedule classes or sessions','Collect payments','Publish lessons and resources','Track attendance and progress','Grade or review submissions','Issue certificates','Manage instructors','View enrollment reports'], problems:['Enrollment is too manual','Course content is spread across tools','Payments and enrollments do not match','Student communication is inconsistent','Progress is difficult to track','Certificates require manual work','Scheduling creates conflicts','Instructor access is difficult to manage','The website does not explain programs clearly','Monthly platform costs are too high'] },
  media: { label:'Creator, media, and personal brand', types:['Content creator','Podcast','Artist or entertainer','Speaker or author','Influencer','Media company','Photographer or videographer','Newsletter brand','Community brand','Other personal or media brand'], platforms:['YouTube','Instagram','TikTok','Patreon','Substack','Spotify','Apple Podcasts','Shopify','Squarespace','WordPress','Mailchimp','ConvertKit'], customer:['View content','Subscribe to updates','Join a membership','Buy merchandise','Book an appearance','Request a partnership','Access premium content','Register for events','Support the brand','Contact the team'], owner:['Publish content','Manage subscribers','Sell products','Manage memberships','Collect partnership inquiries','Schedule releases','Manage events','Track sponsorships','Send newsletters','View audience reports'], problems:['Content is spread across platforms','The brand does not own its audience data','Sponsorship inquiries are disorganized','Membership and content access are disconnected','Merchandise is difficult to manage','The website does not reflect the brand','Email growth is slow','Publishing takes too much manual work','Analytics are fragmented','Too many subscriptions are required'] },
  technology: { label:'Technology, software, and online platforms', types:['Software-as-a-service product','Marketplace','Mobile or web app','Technology consultancy','Internal business platform','Data or analytics product','AI product','Developer tool','Digital membership platform','Other technology business'], platforms:['Stripe','Firebase','Supabase','AWS','Google Cloud','Azure','GitHub','HubSpot','Intercom','Auth0','SendGrid','Twilio'], customer:['Create an account','Subscribe to a plan','Use a dashboard','Manage billing','Invite team members','Upload or manage data','Receive notifications','Contact support','Access documentation','Integrate other tools'], owner:['Manage users and permissions','Manage plans and billing','View product analytics','Handle support requests','Manage content or configuration','Send notifications','Review logs and activity','Control integrations','Manage teams or organizations','Create reports'], problems:['The product is difficult to onboard','Billing and access are disconnected','Admin tools are incomplete','Support requests are hard to track','User permissions are too limited','Analytics do not answer key questions','Manual operations do not scale','Integrations are fragile','The interface is difficult on mobile','Infrastructure costs are unclear'] },
  other: { label:'Other or mixed business model', types:['Service business','Product business','Membership organization','Event-based business','Marketplace','Internal operation','Combination of services and products','Other'], platforms:sharedPlatforms, customer:['Learn about the business','View services or products','Request a quote','Book or register','Make a payment','Create an account','Upload information','Access resources','Receive updates','Contact the business'], owner:['Manage customers or members','Manage services or products','Manage bookings or registrations','Collect payments','Store forms and documents','Send follow-up','Manage staff access','Publish content','Track activity','View reports'], problems:['Too much manual work','Too many disconnected tools','High monthly software costs','Customer follow-up is inconsistent','Information is difficult to find','The current website is unclear','Payments and records do not match','Staff access is difficult to manage','Reporting is limited','The current setup cannot support growth'] }
};

const state = {
  index:0,path:'',contact:{},industry:'',businessType:'',offerModels:[],
  currentWebsite:'',currentApp:'',domainAccess:'',adminAccess:'',currentManager:'',
  selectedPlatforms:[],platformPlan:'',requiredIntegrations:[],
  customerFeatures:[],ownerFeatures:[],problems:[],goals:[],
  paymentModels:[],migrationTypes:[],migrationVolume:'',
  brandReadiness:'',contentAssets:[],contentResponsibility:'',
  userRoles:[],permissionLevels:'',sensitiveData:[],compliance:[],
  communications:[],reportingNeeds:[],
  employeeCount:'',internalUsers:[],locations:'',customerVolume:'',
  supportNeeds:[],ownershipPreference:'',
  currentMonthlyCost:'',monthlyBudget:'',projectBudget:'',timeline:'',requiredLaunchDate:'',launchDependency:'',
  decisionStatus:'',approvalProcess:'',success:'',additionalNotes:''
};

const wizard=document.querySelector('#wizard');
const thankYou=document.querySelector('#thankYou');
const back=document.querySelector('#backButton');
const next=document.querySelector('#nextButton');
const progress=document.querySelector('#progressBar');
const progressLabel=document.querySelector('#progressLabel');
const stepLabel=document.querySelector('#stepLabel');
const error=document.querySelector('#errorMessage');
let steps=[];

function buildSteps(){
  const industry=industries[state.industry];
  steps=[
    step(renderPath,()=>selectedRadio('path')?true:fail('Choose how you want to begin.'),()=>{state.path=selectedRadio('path');buildSteps();}),
    step(renderContact,validateContact,saveContact),
    step(renderIndustry,()=>selectedRadio('industry')?true:fail('Choose the closest industry.'),()=>{state.industry=selectedRadio('industry');resetIndustryAnswers();buildSteps();})
  ];
  if(industry){
    steps.push(
      singleStep('Business type','Which option best describes the business?','businessType',industry.types),
      multiStep('Business model','What does the business primarily offer?','offerModels',['Services','Physical products','Digital products','Appointments','Memberships','Courses or training','Events or registrations','Donations or sponsorships','Subscriptions','Marketplace transactions','Multiple types'])
    );
    if(state.path==='improve'){
      steps.push(
        step(renderCurrentSetup,validateCurrentSetup,saveCurrentSetup),
        multiStep('Current platforms','Which platforms or tools do you currently use?','selectedPlatforms',unique([...industry.platforms,...sharedPlatforms])),
        singleStep('Platform direction','How should the existing platforms be handled?','platformPlan',['Keep the essential tools connected','Replace as much as practical','Consolidate overlapping tools','Migrate gradually','Evaluate each platform and recommend the best path']),
        multiStep('Current challenges','What is not working well today?','problems',industry.problems)
      );
    }
    steps.push(
      multiStep(state.path==='start'?'Customer experience':'Customer experience to improve',state.path==='start'?'What should customers be able to do?':'Which customer-facing capabilities should the improved system support?','customerFeatures',industry.customer),
      multiStep(state.path==='start'?'Owner and team tools':'Operations to improve',state.path==='start'?'What should the owner or team be able to manage?':'Which internal capabilities should the improved system support?','ownerFeatures',industry.owner)
    );
    if(state.path==='start')steps.push(multiStep('Project priorities','What should the new digital foundation accomplish first?','goals',startGoals(industry)));
  }
  steps.push(
    multiStep('Payments and revenue','How does the business charge or receive money?','paymentModels',['One-time payments','Deposits','Recurring subscriptions','Membership dues','Payment plans','Invoices','Donations','Marketplace commissions','Free service with lead generation','No online payments']),
    multiStep('Integrations','Which systems should remain connected?','requiredIntegrations',['Accounting','Email marketing','CRM','Calendar','Payment processor','Inventory','Point of sale','Shipping','Existing database','Google Sheets','Social platforms','Third-party API','No integrations needed','Unsure']),
    step(renderMigration,validateMigration,saveMigration),
    step(renderBrandContent,validateBrandContent,saveBrandContent),
    step(renderRolesSecurity,validateRolesSecurity,saveRolesSecurity),
    step(renderCommunicationReporting,validateCommunicationReporting,saveCommunicationReporting),
    step(renderBusinessProfile,validateBusinessProfile,saveBusinessProfile),
    step(renderSupportOwnership,validateSupportOwnership,saveSupportOwnership),
    step(renderBudget,validateBudget,saveBudget),
    step(renderDecision,validateDecision,saveDecision),
    step(renderReview,()=>true,()=>{})
  );
}

function step(render,validate,save){return{render,validate,save};}
function singleStep(eyebrow,title,key,values){return step(()=>optionScreen(eyebrow,title,'Choose the closest answer.',key,values,false),()=>selectedRadio(key)?true:fail('Choose one option.'),()=>{state[key]=selectedRadio(key);});}
function multiStep(eyebrow,title,key,values){return step(()=>optionScreen(eyebrow,title,'Select all that apply.',key,values,true),()=>checked(key).length?true:fail('Select at least one option.'),()=>{state[key]=checked(key);});}

function renderPath(){return `<p class="eyebrow">Choose your path</p><h1>How should we approach your project?</h1><p class="lead">Your choice changes the questions that follow.</p><fieldset class="form-area"><legend>Choose one</legend><div class="path-choice-grid">${pathCard('start','Start From Scratch','Create a new website, app, store, portal, automation, or complete digital foundation.','New business or new build')}${pathCard('improve','Build It Better','Improve, replace, connect, or consolidate an existing website, platform, app, or workflow.','Existing setup')}</div></fieldset>`;}
function pathCard(value,title,copy,kicker){return `<div class="path-choice"><input id="path-${value}" name="path" type="radio" value="${value}" ${state.path===value?'checked':''}><label for="path-${value}"><span>${kicker}</span><strong>${title}</strong><small>${copy}</small></label></div>`;}
function renderContact(){return `<p class="eyebrow">Contact</p><h2>Where should we send your confirmation?</h2><p class="lead">We will use this information to identify the project and follow up.</p><div class="form-area"><div class="field"><label for="businessName">Business or project name</label><input id="businessName" type="text" value="${esc(state.contact.businessName||'')}" autocomplete="organization"></div><div class="field"><label for="contactName">Your name</label><input id="contactName" type="text" value="${esc(state.contact.contactName||'')}" autocomplete="name"></div><div class="field"><label for="contactEmail">Email address</label><input id="contactEmail" type="email" value="${esc(state.contact.contactEmail||'')}" autocomplete="email" inputmode="email"></div></div>`;}
function renderIndustry(){return `<p class="eyebrow">Industry</p><h2>What type of business is this?</h2><p class="lead">Choose the closest match. The remaining questions will adapt to this industry.</p><fieldset class="form-area"><legend>Choose one</legend><div class="choices two">${Object.entries(industries).map(([key,item],i)=>radio('industry',`industry-${i}`,item.label,state.industry===key,key)).join('')}</div></fieldset>`;}
function optionScreen(eyebrow,title,description,key,values,isMulti){const selected=Array.isArray(state[key])?state[key]:[];return `<p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p class="lead">${description}</p><fieldset class="form-area"><legend>${isMulti?'Select all that apply':'Choose one'}</legend><div class="choices two">${values.map((v,i)=>isMulti?choice(key,`${key}-${i}`,v,selected.includes(v)):radio(key,`${key}-${i}`,v,state[key]===v)).join('')}</div></fieldset>`;}

function renderCurrentSetup(){return `<p class="eyebrow">Current setup</p><h2>What already exists?</h2><p class="lead">These details help us review the current experience and understand access constraints.</p><div class="form-area"><div class="field"><label for="currentWebsite">Current website URL</label><input id="currentWebsite" type="url" value="${esc(state.currentWebsite)}" placeholder="https://example.com"></div><div class="field"><label for="currentApp">App, portal, or platform URL (optional)</label><input id="currentApp" type="url" value="${esc(state.currentApp)}" placeholder="https://app.example.com"></div><fieldset><legend>Domain access</legend><div class="choices">${['I control the domain account','Someone else controls it','I am not sure','No domain yet'].map((v,i)=>radio('domainAccess',`domain-${i}`,v,state.domainAccess===v)).join('')}</div></fieldset><fieldset><legend>Administrative access</legend><div class="choices">${['I have full administrator access','I have limited access','A vendor or employee has access','I do not have access','I am not sure'].map((v,i)=>radio('adminAccess',`admin-${i}`,v,state.adminAccess===v)).join('')}</div></fieldset><div class="field"><label for="currentManager">Who currently hosts or manages it?</label><input id="currentManager" type="text" value="${esc(state.currentManager)}" placeholder="Company, employee, vendor, or unsure"></div></div>`;}
function validateCurrentSetup(){if(!value('currentWebsite')&&!value('currentApp'))return fail('Enter the current website or platform URL.');if(!selectedRadio('domainAccess'))return fail('Select the domain access status.');if(!selectedRadio('adminAccess'))return fail('Select the administrative access status.');return true;}
function saveCurrentSetup(){state.currentWebsite=value('currentWebsite');state.currentApp=value('currentApp');state.domainAccess=selectedRadio('domainAccess');state.adminAccess=selectedRadio('adminAccess');state.currentManager=value('currentManager');}

function renderMigration(){const needsMigration=state.path==='improve';return `<p class="eyebrow">Data migration</p><h2>${needsMigration?'What information must move to the improved system?':'Will an existing source provide data or content?'}</h2><p class="lead">Migration volume can materially affect project scope and testing.</p><div class="form-area"><fieldset><legend>Select all that apply</legend><div class="choices two">${['Customer or client records','Appointments or schedules','Products and inventory','Orders and payment records','Memberships or subscriptions','Forms and submissions','Documents or uploaded files','Website pages or blog posts','Email subscribers','No migration needed','Unsure'].map((v,i)=>choice('migrationTypes',`migration-${i}`,v,state.migrationTypes.includes(v))).join('')}</div></fieldset><div class="field"><label for="migrationVolume">Approximate number of records</label><select id="migrationVolume"><option value="">Select a range</option>${options(['No records to migrate','Under 100','100-1,000','1,001-10,000','More than 10,000','Unsure'],state.migrationVolume)}</select></div></div>`;}
function validateMigration(){if(!checked('migrationTypes').length)return fail('Select the migration requirement.');if(!value('migrationVolume'))return fail('Select the approximate record volume.');return true;}
function saveMigration(){state.migrationTypes=checked('migrationTypes');state.migrationVolume=value('migrationVolume');}

function renderBrandContent(){return `<p class="eyebrow">Brand and content</p><h2>How prepared are the brand and project materials?</h2><div class="form-area"><fieldset><legend>Brand readiness</legend><div class="choices">${['Brand is complete with logo and guidelines','Logo exists but the brand needs refinement','Colors and direction exist but are incomplete','Full brand identity is needed','Existing brand must remain unchanged','Unsure'].map((v,i)=>radio('brandReadiness',`brand-${i}`,v,state.brandReadiness===v)).join('')}</div></fieldset><fieldset><legend>Available content and assets</legend><div class="choices two">${['Logo files','Brand guidelines','Website copy','Product or service descriptions','Photography','Videos','Testimonials or reviews','Staff biographies','Policies or legal text','Existing content that can be reused','Very little is ready'].map((v,i)=>choice('contentAssets',`asset-${i}`,v,state.contentAssets.includes(v))).join('')}</div></fieldset><fieldset><legend>Who should prepare the content?</legend><div class="choices">${['Client will provide everything','Alpha Zone Labs should organize and revise it','Alpha Zone Labs should create most of it','Shared responsibility','Unsure'].map((v,i)=>radio('contentResponsibility',`content-owner-${i}`,v,state.contentResponsibility===v)).join('')}</div></fieldset></div>`;}
function validateBrandContent(){if(!selectedRadio('brandReadiness'))return fail('Select the brand readiness.');if(!checked('contentAssets').length)return fail('Select the available content.');if(!selectedRadio('contentResponsibility'))return fail('Select who should prepare the content.');return true;}
function saveBrandContent(){state.brandReadiness=selectedRadio('brandReadiness');state.contentAssets=checked('contentAssets');state.contentResponsibility=selectedRadio('contentResponsibility');}

function renderRolesSecurity(){return `<p class="eyebrow">Users, security, and compliance</p><h2>Who needs access, and what information will the system handle?</h2><div class="form-area"><fieldset><legend>User roles</legend><div class="choices two">${['Owner or super-admin','Manager','Employee or provider','Contractor','Customer or member','Parent or guardian','Volunteer','Vendor','Multiple organizations or locations'].map((v,i)=>choice('userRoles',`role-${i}`,v,state.userRoles.includes(v))).join('')}</div></fieldset><fieldset><legend>Permission requirements</legend><div class="choices">${['Everyone can use the same access level','Different roles need different permissions','Location-based access is required','Approval workflows are required','Unsure'].map((v,i)=>radio('permissionLevels',`permission-${i}`,v,state.permissionLevels===v)).join('')}</div></fieldset><fieldset><legend>Sensitive information handled</legend><div class="choices two">${['Health or medical information','Children or minors information','Financial information','Identity documents','Background checks','Confidential client files','Employee records','No sensitive information','Unsure'].map((v,i)=>choice('sensitiveData',`sensitive-${i}`,v,state.sensitiveData.includes(v))).join('')}</div></fieldset><fieldset><legend>Known requirements</legend><div class="choices two">${['HIPAA','FERPA','COPPA','PCI or payment compliance','Accessibility requirements','Data retention rules','Industry-specific regulation','No known requirements','Unsure'].map((v,i)=>choice('compliance',`compliance-${i}`,v,state.compliance.includes(v))).join('')}</div></fieldset></div>`;}
function validateRolesSecurity(){if(!checked('userRoles').length)return fail('Select the user roles.');if(!selectedRadio('permissionLevels'))return fail('Select the permission requirement.');if(!checked('sensitiveData').length)return fail('Select the sensitive-data status.');if(!checked('compliance').length)return fail('Select the compliance status.');return true;}
function saveRolesSecurity(){state.userRoles=checked('userRoles');state.permissionLevels=selectedRadio('permissionLevels');state.sensitiveData=checked('sensitiveData');state.compliance=checked('compliance');}

function renderCommunicationReporting(){return `<p class="eyebrow">Communication and reporting</p><h2>What should the system send and measure?</h2><div class="form-area"><fieldset><legend>Communication channels</legend><div class="choices two">${['Transactional email','Marketing email','SMS or text messaging','Push notifications','Internal alerts','Automated reminders','Two-way messaging','Customer support chat','No automated communication'].map((v,i)=>choice('communications',`communication-${i}`,v,state.communications.includes(v))).join('')}</div></fieldset><fieldset><legend>Reporting needs</legend><div class="choices two">${['Leads and inquiries','Bookings or appointments','Sales and revenue','Registrations or attendance','Customer retention','Inventory','Staff performance','Marketing attribution','Donations or sponsorships','Program outcomes','Custom dashboards','Basic analytics only'].map((v,i)=>choice('reportingNeeds',`report-${i}`,v,state.reportingNeeds.includes(v))).join('')}</div></fieldset></div>`;}
function validateCommunicationReporting(){if(!checked('communications').length)return fail('Select the communication requirements.');if(!checked('reportingNeeds').length)return fail('Select the reporting requirements.');return true;}
function saveCommunicationReporting(){state.communications=checked('communications');state.reportingNeeds=checked('reportingNeeds');}

function renderBusinessProfile(){return `<p class="eyebrow">Business profile</p><h2>Help us understand the size of the operation.</h2><div class="form-area"><div class="field"><label for="employeeCount">Number of employees or regular team members</label><select id="employeeCount"><option value="">Select a range</option>${options(['Sole owner or operator','2-5 employees','6-10 employees','11-25 employees','26-50 employees','More than 50 employees'],state.employeeCount)}</select></div><fieldset><legend>Who will use the system internally?</legend><div class="choices two">${['Owner only','Owner and managers','Employees or service providers','Contractors','Volunteers','Multiple departments','Franchisees or locations'].map((v,i)=>choice('internalUsers',`internal-${i}`,v,state.internalUsers.includes(v))).join('')}</div></fieldset><div class="field"><label for="locations">Locations or service model</label><select id="locations"><option value="">Select one</option>${options(['Online only','One physical location','2-5 physical locations','More than 5 physical locations','Mobile or service-area business','Multiple cities or markets'],state.locations)}</select></div><div class="field"><label for="customerVolume">Approximate monthly customer volume</label><select id="customerVolume"><option value="">Select a range</option>${options(['Fewer than 25','25-100','101-250','251-500','More than 500','Unsure'],state.customerVolume)}</select></div></div>`;}
function validateBusinessProfile(){if(!value('employeeCount'))return fail('Select the team size.');if(!checked('internalUsers').length)return fail('Select who will use the system.');if(!value('locations'))return fail('Select the location model.');if(!value('customerVolume'))return fail('Select the customer volume.');return true;}
function saveBusinessProfile(){state.employeeCount=value('employeeCount');state.internalUsers=checked('internalUsers');state.locations=value('locations');state.customerVolume=value('customerVolume');}

function renderSupportOwnership(){return `<p class="eyebrow">Launch and ongoing support</p><h2>What should happen after the initial build?</h2><div class="form-area"><fieldset><legend>Ongoing support needs</legend><div class="choices two">${['Hosting','Domain management','Maintenance and security updates','Content updates','Technical support','Staff training','Analytics reporting','Automation management','No ongoing support','Unsure'].map((v,i)=>choice('supportNeeds',`support-${i}`,v,state.supportNeeds.includes(v))).join('')}</div></fieldset><fieldset><legend>Account and code ownership preference</legend><div class="choices">${['Client should own all accounts and assets','Alpha Zone Labs may manage accounts on our behalf','Shared management','Needs to be discussed'].map((v,i)=>radio('ownershipPreference',`ownership-${i}`,v,state.ownershipPreference===v)).join('')}</div></fieldset></div>`;}
function validateSupportOwnership(){if(!checked('supportNeeds').length)return fail('Select the ongoing support needs.');if(!selectedRadio('ownershipPreference'))return fail('Select the ownership preference.');return true;}
function saveSupportOwnership(){state.supportNeeds=checked('supportNeeds');state.ownershipPreference=selectedRadio('ownershipPreference');}

function renderBudget(){const current=state.path==='improve'?`<div class="field"><label for="currentMonthlyCost">Current monthly software cost</label><select id="currentMonthlyCost"><option value="">Select a range</option>${options(['Not currently paying for software','Under $50','$50-$100','$101-$250','$251-$500','More than $500','Unsure'],state.currentMonthlyCost)}</select></div>`:'';return `<p class="eyebrow">Budget and timing</p><h2>What investment range fits the business?</h2><p class="lead">Choose the closest range. This helps us recommend the right scope, not automatically the highest option.</p><div class="form-area">${current}<div class="field"><label for="monthlyBudget">Preferred monthly operating cost</label><select id="monthlyBudget"><option value="">Select a range</option>${options(['Under $25','$25-$50','$51-$100','$101-$250','More than $250','Recommend the appropriate range'],state.monthlyBudget)}</select></div><div class="field"><label for="projectBudget">Target design and development budget</label><select id="projectBudget"><option value="">Select a range</option>${options(['Under $500','$500-$1,000','$1,001-$2,500','$2,501-$5,000','$5,001-$10,000','$10,001-$20,000','$20,001-$40,000','More than $40,000','Needs to be discussed'],state.projectBudget)}</select></div><fieldset><legend>Preferred launch timing</legend><div class="choices">${['As soon as possible','Within 30 days','Within 60-90 days','Within 3-6 months','More than 6 months','No firm deadline'].map((v,i)=>radio('timeline',`timeline-${i}`,v,state.timeline===v)).join('')}</div></fieldset><div class="field"><label for="requiredLaunchDate">Required launch date (optional)</label><input id="requiredLaunchDate" type="date" value="${esc(state.requiredLaunchDate)}"></div><div class="field"><label for="launchDependency">What is the date tied to? (optional)</label><input id="launchDependency" type="text" value="${esc(state.launchDependency)}" placeholder="Opening, event, season, campaign, contract, or funding deadline"></div></div>`;}
function validateBudget(){if(state.path==='improve'&&!value('currentMonthlyCost'))return fail('Select the current monthly software cost.');if(!value('monthlyBudget')||!value('projectBudget'))return fail('Select both budget ranges.');if(!selectedRadio('timeline'))return fail('Select a launch timeframe.');return true;}
function saveBudget(){state.currentMonthlyCost=value('currentMonthlyCost');state.monthlyBudget=value('monthlyBudget');state.projectBudget=value('projectBudget');state.timeline=selectedRadio('timeline');state.requiredLaunchDate=value('requiredLaunchDate');state.launchDependency=value('launchDependency');}

function renderDecision(){const industry=industries[state.industry];const outcomes=unique([...(industry?industry.customer.slice(0,3):[]),'More leads or inquiries','More bookings, registrations, or sales','Better customer experience','Lower software costs','Less manual work','Better reporting','Easier staff management','Support future growth','A combination of these outcomes']);return `<p class="eyebrow">Readiness and success</p><h2>What should happen after this form?</h2><div class="form-area"><fieldset><legend>Decision status</legend><div class="choices">${['Ready to begin','Comparing options','Planning for a future project','Gathering information for leadership','Unsure what solution is needed'].map((v,i)=>radio('decisionStatus',`decision-${i}`,v,state.decisionStatus===v)).join('')}</div></fieldset><fieldset><legend>Approval process</legend><div class="choices">${['I am the final decision-maker','One other person must approve','Leadership or a board must approve','Procurement or legal review is required','Funding or sponsorship must be secured','Unsure'].map((v,i)=>radio('approvalProcess',`approval-${i}`,v,state.approvalProcess===v)).join('')}</div></fieldset><fieldset><legend>Primary measure of success</legend><div class="choices two">${outcomes.map((v,i)=>radio('success',`success-${i}`,v,state.success===v)).join('')}</div></fieldset><div class="field"><label for="additionalNotes">Anything else we should know? (optional)</label><textarea id="additionalNotes" placeholder="Important context, constraints, examples, competitors, or links">${esc(state.additionalNotes)}</textarea></div></div>`;}
function validateDecision(){if(!selectedRadio('decisionStatus'))return fail('Select the decision status.');if(!selectedRadio('approvalProcess'))return fail('Select the approval process.');if(!selectedRadio('success'))return fail('Select the primary measure of success.');return true;}
function saveDecision(){state.decisionStatus=selectedRadio('decisionStatus');state.approvalProcess=selectedRadio('approvalProcess');state.success=selectedRadio('success');state.additionalNotes=value('additionalNotes');}

function renderReview(){const industry=industries[state.industry];return `<p class="eyebrow">Review</p><h2>Ready to submit?</h2><p class="lead">Review the major details below. Use Back to make changes.</p><div class="review-grid">${review('Project path',state.path==='start'?'Start From Scratch':'Build It Better')}${review('Business',state.contact.businessName)}${review('Contact',state.contact.contactName)}${review('Email',state.contact.contactEmail)}${review('Industry',industry?.label)}${review('Business type',state.businessType)}${review('Business model',state.offerModels.join(', '))}${state.path==='improve'?review('Current website',state.currentWebsite):''}${state.path==='improve'?review('Current platforms',state.selectedPlatforms.join(', ')):''}${review('Customer capabilities',state.customerFeatures.join(', '))}${review('Owner capabilities',state.ownerFeatures.join(', '))}${review('Payments',state.paymentModels.join(', '))}${review('Integrations',state.requiredIntegrations.join(', '))}${review('Migration',state.migrationTypes.join(', '))}${review('Brand readiness',state.brandReadiness)}${review('Sensitive data',state.sensitiveData.join(', '))}${review('Compliance',state.compliance.join(', '))}${review('Team size',state.employeeCount)}${review('Locations',state.locations)}${review('Project budget',state.projectBudget)}${review('Launch timing',state.timeline)}${review('Decision status',state.decisionStatus)}${review('Approval',state.approvalProcess)}${review('Success priority',state.success)}</div>`;}

function validateContact(){const b=value('businessName'),n=value('contactName'),e=value('contactEmail');if(!b||!n||!e)return fail('Complete all contact fields.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))return fail('Enter a valid email address.');return true;}
function saveContact(){state.contact={businessName:value('businessName'),contactName:value('contactName'),contactEmail:value('contactEmail')};}
function resetIndustryAnswers(){state.businessType='';state.selectedPlatforms=[];state.customerFeatures=[];state.ownerFeatures=[];state.problems=[];state.goals=[];}

function render(){error.textContent='';wizard.innerHTML=steps[state.index].render();const current=state.index+1,total=steps.length,pct=Math.round(current/total*100);stepLabel.textContent=`Step ${current} of ${total}`;progressLabel.textContent=`${pct}%`;progress.style.width=`${pct}%`;back.style.visibility=state.index===0?'hidden':'visible';next.textContent=state.index===total-1?'Submit request':'Continue';next.disabled=false;window.scrollTo({top:0,behavior:'smooth'});}
function forward(){const current=steps[state.index];if(!current.validate())return;current.save();if(state.index===steps.length-1){submit();return;}state.index++;render();}
function backward(){if(state.index>0){state.index--;render();}}

function submit(){next.disabled=true;next.textContent='Submitting...';const industry=industries[state.industry];const detailLines=[
  `Project path: ${state.path==='start'?'Start From Scratch':'Build It Better'}`,
  `Industry: ${industry?.label||''}`,
  `Business type: ${state.businessType}`,
  `Business model: ${state.offerModels.join(', ')}`,
  `Current website: ${state.currentWebsite||'Not provided'}`,
  `Current app/platform: ${state.currentApp||'Not provided'}`,
  `Domain access: ${state.domainAccess||'Not applicable'}`,
  `Admin access: ${state.adminAccess||'Not applicable'}`,
  `Current manager: ${state.currentManager||'Not provided'}`,
  `Platform plan: ${state.platformPlan||'Not applicable'}`,
  `Current challenges: ${state.problems.join(', ')||'None listed'}`,
  `Project priorities: ${state.goals.join(', ')||'None listed'}`,
  `Payment models: ${state.paymentModels.join(', ')}`,
  `Required integrations: ${state.requiredIntegrations.join(', ')}`,
  `Migration: ${state.migrationTypes.join(', ')} (${state.migrationVolume})`,
  `Brand readiness: ${state.brandReadiness}`,
  `Content assets: ${state.contentAssets.join(', ')}`,
  `Content responsibility: ${state.contentResponsibility}`,
  `User roles: ${state.userRoles.join(', ')}`,
  `Permissions: ${state.permissionLevels}`,
  `Sensitive data: ${state.sensitiveData.join(', ')}`,
  `Compliance: ${state.compliance.join(', ')}`,
  `Communications: ${state.communications.join(', ')}`,
  `Reporting: ${state.reportingNeeds.join(', ')}`,
  `Team size: ${state.employeeCount}`,
  `Internal users: ${state.internalUsers.join(', ')}`,
  `Locations: ${state.locations}`,
  `Monthly customer volume: ${state.customerVolume}`,
  `Support needs: ${state.supportNeeds.join(', ')}`,
  `Ownership preference: ${state.ownershipPreference}`,
  `Decision status: ${state.decisionStatus}`,
  `Approval process: ${state.approvalProcess}`,
  `Required launch date: ${state.requiredLaunchDate||'Not specified'}`,
  `Launch dependency: ${state.launchDependency||'Not specified'}`,
  `Additional notes: ${state.additionalNotes||'None'}`
];
  const payloadData={
    submittedAt:new Date().toISOString(),contact:state.contact,
    selectedPlatforms:state.path==='improve'?state.selectedPlatforms:['New build / no existing platform'],
    platformResponses:{adaptiveDiscovery:{features:[...state.customerFeatures,...state.ownerFeatures],cost:state.currentMonthlyCost||'Not applicable',future:state.path==='start'?'Build from scratch':state.platformPlan||'Improve or consolidate'}},
    goals:detailLines,customerFeatures:state.customerFeatures,ownerFeatures:state.ownerFeatures,
    transition:state.path==='start'?'Start from scratch':state.platformPlan||'Build it better',
    monthlyBudget:state.monthlyBudget,projectBudget:state.projectBudget,timeline:state.timeline,success:state.success,
    source:'quote.alphazonelabs.com complete adaptive discovery'
  };
  const postForm=document.createElement('form');postForm.method='POST';postForm.action=APPS_SCRIPT_URL;postForm.target='quoteSubmissionFrame';postForm.style.display='none';const payload=document.createElement('input');payload.name='payload';payload.value=JSON.stringify(payloadData);postForm.appendChild(payload);document.body.appendChild(postForm);postForm.submit();
}

function showThanks(){thankYou.hidden=false;document.body.classList.add('modal-open');thankYou.querySelector('a')?.focus();}
window.addEventListener('message',e=>{if(e.data?.type==='ALPHA_QUOTE_SUCCESS')showThanks();if(e.data?.type==='ALPHA_QUOTE_ERROR'){next.disabled=false;next.textContent='Submit request';fail('The request could not be submitted. Please try again.');}});
back.addEventListener('click',backward);next.addEventListener('click',forward);

function startGoals(industry){return unique(['Create a professional online presence','Generate leads or inquiries','Accept bookings or registrations','Sell products or services online','Collect payments or deposits','Organize customer or member records','Reduce manual work','Build trust and credibility','Support future growth',...industry.customer.slice(0,3)]);}
function unique(values){return[...new Set(values)];}
function selectedRadio(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||'';}
function choice(name,id,label,isChecked=false,value=label){return `<div class="choice"><input id="${id}" name="${name}" type="checkbox" value="${esc(value)}" ${isChecked?'checked':''}><label for="${id}">${label}</label></div>`;}
function radio(name,id,label,isChecked=false,value=label){return `<div class="choice radio"><input id="${id}" name="${name}" type="radio" value="${esc(value)}" ${isChecked?'checked':''}><label for="${id}">${label}</label></div>`;}
function checked(name){return[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);}
function value(id){return document.querySelector(`#${id}`)?.value.trim()||'';}
function options(values,selected){return values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${v}</option>`).join('');}
function review(label,val){return `<article class="review-card"><strong>${label}</strong><span>${esc(val||'Not provided')}</span></article>`;}
function fail(message){error.textContent=message;return false;}
function esc(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}

buildSteps();render();